"""Add hashed_password to users

Revision ID: 7686f6a31d8e
Revises: 5087709890ed
Create Date: 2025-06-25 12:59:57.333235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7686f6a31d8e'
down_revision: Union[str, Sequence[str], None] = '5087709890ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'default_hashed_value'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'default_hashed_value'::character varying"))
    # ### end Alembic commands ###
