"""Fix recipe model

Revision ID: 7931ccb32935
Revises: 7686f6a31d8e
Create Date: 2025-06-26 14:52:24.178927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7931ccb32935'
down_revision: Union[str, Sequence[str], None] = '7686f6a31d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
