services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "uvicorn", "app.main:app", "--host", "${HOST}", "--port", "${PORT}", "--reload" ]

    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env


volumes:
  postgres_data:  